### ISSUE TITLE
Looks exactly like Andrea's time tracker app

### ISSUE THREAD

**Issue by ghost** [prezadopedro/app_login_com_firebase#1]
This repo looks exactly like [Flutter & Firebase Course | Code With Andrea](https://github.com/bizz84/time_tracker_flutter_course) updated to Portuguese.

You should credit the original author!

**Comment by prezadopedro** [comment]
I explain at the beginning of READ.ME that the app is the result of Andrea's course on Udemy, it's in Portuguese, apparently you didn't translate

**Comment by coderpedrosilva** [comment]
> This repo looks exactly like [Flutter & Firebase Course | Code With Andrea](https://github.com/bizz84/time_tracker_flutter_course) updated to Portuguese.
> 
> You should credit the original author!

I explain at the beginning of READ.ME that the app is the result of Andrea's course on Udemy, it's in Portuguese, apparently you didn't translate
